### ISSUE TITLE
Bug encountered when launching main branch

### ISSUE THREAD

**Issue by SamarysB** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#100]
![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager/assets/123615626/08ec3e84-4956-4360-bb36-f9cd380e1750)

Source seems to be project file: AddExpensesModal.js

Priority: 5

**Comment by fernandopizarro1** [comment]
We have to add the dependencies so that not everybody has to download the things needed to run the project.  They are right now in the latest pull request: https://github.com/uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager/pull/95

**Comment by SamarysB** [comment]
Have to run the following command in a bash terminal: npm install uuidv4
