### ISSUE TITLE
FIx bug with expense item

### ISSUE THREAD

**Issue by JeanMontesSantiago** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#152]
## Description
the modal container does not properly accommodate the content when the list exceeds a certain number of items. 

![Image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager/assets/70617469/1762edac-1b1b-4c30-b919-15b3a479765a)

**Comment by gabbsv1** [comment]
Fixed bug with expense, income, and expense view.
