### ISSUE TITLE
Wireframe app navigation from homepage

### ISSUE THREAD

**Issue by JorgeRivera94** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#199]
A navigation bar is currently being implemented. To have a reference point for the restructuring and to better communicate this structure to all teams, it was recommended to create wireframes for how the home page will be structured, its elements, and more importantly, the navigation to other sections.

The wireframe must contain the design for the homepage and using the navigation bar to switch to sections like calendar and graphs.

**Comment by Goya01** [comment]
![Wireframe for INSO project](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager/assets/115514654/0536450f-c358-4c95-92cd-16b8e6b020a0)
![Wireframe for INSO project (1)](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager/assets/115514654/96cfd3c1-485e-4827-a4f0-037c75f3d44a)
![Wireframe for INSO project (2)](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager/assets/115514654/1cdc3b5c-5bac-40bc-a803-0dfb1c00afc0)

These are the base wireframes for the project. They can be further edited such as colors, buttons, etc., but the navigation itself, I think its good.
