### ISSUE TITLE
Improved "informing about activities other than implementing an application" from Milestone 1 where previous submission did not follow guidelines

### ISSUE THREAD

**Issue by YanehRuiz** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#215]
Priority: 5 
Difficulty: 2

**Comment by lex939** [comment]
Previously, Section 1.4 contained 3 bullet points. I edited Section 1.4 to include 4 subsets of info detailing activities other than implementing an application and 1 detailing implementation.
