### ISSUE TITLE
[Lecture Topic Task] Add Algebra and closure under operations to M2 documentation

### ISSUE THREAD

**Issue by MiguelBorrero46** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#231]
"The project showcases at least three instances where they've refined a function to enhance its encapsulation. These modifications span both implementation details and domain-specific functions. For instance, within the banking domain, an initial transfer function transfer(from: Account, to: Account, money: Amount) might evolve into transfer(TransferSpecification): (TransferSpecification, Result) after extensive deliberation and iterations. This refined function not only covers the same scenarios as the original signature but also addresses potential failures (captured in the Result) or partial transfers. This evolution ensures that the application of such a pattern enhances the overall model and design, fostering greater adaptability and resilience within the project's architecture."

https://docs.google.com/document/d/1X330Y0vuRzW2dBmhsBjCv16sUkUu5Rhpxii2oGhCnv4/edit

Priority: 5
Complexity: 2

**Comment by AngelCIICMorales** [comment]
I finished it.
