### ISSUE TITLE
[Lecture Topic Task] Add Agile structuring to Milestone 2 Documentation

### ISSUE THREAD

**Issue by YanehRuiz** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#233]
The project shows how they use sprints to structure the work, use a product backlog and sprint backlogs, maintain the backlogs feature-oriented, and do sprint review and planning.

https://docs.google.com/document/d/1X330Y0vuRzW2dBmhsBjCv16sUkUu5Rhpxii2oGhCnv4/edit

Priority: 5
Complexity: 2

**Comment by fernandopizarro1** [comment]
New Section : Agile Development
