### ISSUE TITLE
[Lecture Topic Task] Created risk analysis 

### ISSUE THREAD

**Issue by YanehRuiz** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#235]
* Identify and assess risks
* Develop risk management plan and document risks

https://docs.google.com/document/d/1X330Y0vuRzW2dBmhsBjCv16sUkUu5Rhpxii2oGhCnv4/edit

Priority: 5
Complexity: 2

**Comment by lex939** [comment]
Created - Section 3.4
