### ISSUE TITLE
[Lecture Topic Task] Created Engineering Requirements

### ISSUE THREAD

**Issue by YanehRuiz** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#236]
Requirements engineering:
Identify and prioritize requirements
Develop use cases and scenarios
Perform requirements analysis and modeling

https://docs.google.com/document/d/1X330Y0vuRzW2dBmhsBjCv16sUkUu5Rhpxii2oGhCnv4/edit

Priority: 5
Complexity: 2

**Comment by lex939** [comment]
New Section - 2.2.6
