### ISSUE TITLE
Data_Entry UI

### ISSUE THREAD

**Issue by Cruiz102** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#26]
Create the UI for the data entry feature. Use the following screenshot as a starting point to model the application. The code should include a state management system in Next.js to handle total incomes and expenses, and categorize them based on a predefined set of categories.
 

![Image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager/assets/65771578/0f34562d-95cb-4197-a944-34e492f71c46)

**Comment by yadrielsamir** [comment]
Can users add custom categories, or are they limited to the predefined set?

**Comment by Cruiz102** [comment]
Ideally, the user can select their own preferred categories. But for now, let's start by giving some predefined initial categories.
