### ISSUE TITLE
Add M3 documentation for Stakeholders 

### ISSUE THREAD

**Issue by MiguelBorrero46** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#266]
Identifying and describing the various stakeholders whose interests and requirements are pivotal for the success of the project. This involves a detailed examination of the project's domain to ascertain the specific needs, expectations, and impacts on these stakeholders, ensuring that all planning and execution strategies are meticulously aligned with these insights to achieve optimal outcomes.

https://docs.google.com/document/d/1oj93v_52P4_3Ni0Ssja2pPf-VpD5xYrlI0MqEeT8CDo/edit

Priority: 3
Complexity: 2

**Comment by lex939** [comment]
Added as section 2.1.8 Stakeholder Information
