### ISSUE TITLE
Add M3 documentation for Domain facets

### ISSUE THREAD

**Issue by MiguelBorrero46** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#268]
The team has explored relevant domain facets. For example, in a project concerned with supermarket checkout a team might want to talk about scanning devices (support technology). But that team might not have anything to say concerning the scripts facet. Relevance needs to be considered in the assessment. Teams should demonstrate that they can judge relevance and not create filler. 

https://docs.google.com/document/d/1oj93v_52P4_3Ni0Ssja2pPf-VpD5xYrlI0MqEeT8CDo/edit

Priority: 3
Complexity: 2

**Comment by lex939** [comment]
Added Section 2.1.9: Domain Facets
