### ISSUE TITLE
Add M3 documentation for Business processes

### ISSUE THREAD

**Issue by MiguelBorrero46** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#269]
The team describes at least one relevant and substantial business process from the domain for each stakeholder group.

https://docs.google.com/document/d/1oj93v_52P4_3Ni0Ssja2pPf-VpD5xYrlI0MqEeT8CDo/edit

Priority: 3
Complexity: 2

**Comment by lex939** [comment]
Added Section 2.1.8: Business Processes
