### ISSUE TITLE
Add M3 documentation for Interface Requirements

### ISSUE THREAD

**Issue by YanehRuiz** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#271]
The team analyzes and documents the shared data initialization and update requirements, the man-machine and the machine-machine dialog requirements, and the physiological requirements.

https://docs.google.com/document/d/1oj93v_52P4_3Ni0Ssja2pPf-VpD5xYrlI0MqEeT8CDo/edit

Priority: 5
Complexity: 2

**Comment by lex939** [comment]
This section (2.2.4) has been rewritten and now mentions important terms mentioned in the description of this issue.
