### ISSUE TITLE
Add M3 documentation for Software Design

### ISSUE THREAD

**Issue by YanehRuiz** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#273]
The team analyzes the requirements and identifies and documents components that collaborate to satisfy the requirements. There is at least one major business process that the team uses as a scenario to validate the design.

https://docs.google.com/document/d/1oj93v_52P4_3Ni0Ssja2pPf-VpD5xYrlI0MqEeT8CDo/edit

Priority: 5
Complexity: 2

**Comment by lex939** [comment]
Documentation for Software Design added as a new section (1.4.3)
