### ISSUE TITLE
[Lecture Topic Task] Domain Engineering

### ISSUE THREAD

**Issue by MiguelBorrero46** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#275]
Domain engineering is a process that explores a domain model, creates a domain description, and works towards a domain theory. It involves switching between different "mindsets" within a sprint as needed.

https://docs.google.com/document/d/1oj93v_52P4_3Ni0Ssja2pPf-VpD5xYrlI0MqEeT8CDo/edit

Priority: 3
Complexity: 2

**Comment by lex939** [comment]
Reworked 1.4.1 Domain Engineering and Requirements Engineering in a way that fits the issue's description best
