### ISSUE TITLE
Create a graph of the linear regression implementation(income)

### ISSUE THREAD

**Issue by JeanMontesSantiago** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#298]
### Background
After implementing an algorithm that performs linear regression on the data, it would be more beneficial to create a chart that displays the line generated by the regression.

### Objective
Create a chart that represents the linear regression of **income**.

### Design
In the data analysis table, create a modal to present the chart. The generated chart should be **green** if the slope of the line is greater than zero and **red**  if it is less.

**Comment by Cruiz102** [comment]
For implementing this I would recommend to use the following Javacript library. Its lightweight and easy to install. I would not recommend using Tensorflow for this its a very large library that problably we dont need.
https://github.com/Tom-Alexander/regression-js
