### ISSUE TITLE
[Lecture Topic Task] CEN to describe app navigation

### ISSUE THREAD

**Issue by JorgeRivera94** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#316]
A Condition Event Network will be created to describe and test the user's navigation through the app. The Petri net could use transitions to represent navigating to a certain page within the app, and places as the required states and conditions that need to be met for navigating to that page.

Additional to the "Petri Nets" section in Moodle, these two videos by Purdue professor Dr Richard Voyles could serve as additional resources to better understand PetriNet usage.
https://youtu.be/GCsVxWh995o?si=xQG46SW-53G3PfO1
https://youtu.be/WGSAi9-QUwk?si=0_hgtQ2_YhRtkt-z

**Comment by DavidCuevas3** [comment]
Added the task to the documentation, closing issue as done
![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager/assets/94259388/ed5d4dee-2b54-42e2-9a5a-2082c24499e4)
