### ISSUE TITLE
Improving Events, Actions, and Behaviors from M2

### ISSUE THREAD

**Issue by YanehRuiz** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#347]
Professor feedback:

Events:

    Events like "user creates" and "adding" take an actor and time to perform.
    Related events like "a new saving goal has just been created" mark the end of an action and are instantaneous.
    These events help define the domain's timeline and actions.

Categorize Expenses:

    This action needs a more detailed explanation of its functionality.
    It should involve concepts like categories, categorization, and mapping expenses/incomes to categories.
    This explanation clarifies how these concepts interact within the domain.

Behaviors:

    Behaviors are composed of actions and events, but only those relevant to the domain and abstraction level.
    For example, "bring records up-to-date" is a meaningful behavior with specific actions and events.
    Reviewing other behaviors ensures their relevance and component actions/events

Priority: 5
Complexity: 2

https://docs.google.com/document/d/1oj93v_52P4_3Ni0Ssja2pPf-VpD5xYrlI0MqEeT8CDo/edit

**Comment by dAninAd1248** [comment]
Done

**Comment by dAninAd1248** [comment]
Done
