### ISSUE TITLE
Create Homepage UI

### ISSUE THREAD

**Issue by Lennon0926** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#38]
## Objective:
The goal of this task is to improve the user experience on the home page of the website/app. This will be achieved by improving the design of the user interface, creating layouts for the buttons and creating a modal.

## Description:
**The task will focus on the following areas:**

-**User Interface Design:** The overall design of the home page will be improved, including typography, use of color, visual hierarchy, and spacing.
-**Button layouts:** Layouts will be created for the main buttons on the home page, including the call to action (CTA) button and other important buttons.
-**Modal:** A modal will be created to provide additional information or to request information from the user.

## Deliverables:

**The deliverables of the task will be the following:**

-**User Interface Design:** A visual design of the updated home page will be created.
-**Button layouts:** Layouts will be created for the main buttons on the home page.
-**Modal:** A functional modal with relevant content will be created.

**Difficulty**: 3
**Urgency**: 5

**Comment by JorgeRivera94** [comment]
Worked directly to main under the supervision of team leaders due to complex merge conflicts.
