### ISSUE TITLE
Button accesses in the UI

### ISSUE THREAD

**Issue by Fernando2908** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#39]
## **Objective:**
Allow the user to access the categories and remove one or more transactions from it

## **Background:**
Show the user the transaction history of the selected category and allow the user to delete the desired transaction.

## **Requirements:**
Create access to category buttons:
- Allow the user to access a category.
- Enable the user to view transaction historial.

Difficulty: 3
Urgency: 5

**Comment by JorgeRivera94** [comment]
Pushed directly to main under the supervision of team leaders due to complex merge conflicts.
