### ISSUE TITLE
Basic Login UI and Functionality

### ISSUE THREAD

**Issue by Goya01** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#41]
Made a basic UI of a login page where user can input their email and password. Also, made a show Password button in case users want to see their password input.

**Comment by DavidCuevas3** [comment]
> Podemos de una vez implementar un _Forgot Password Functionality_ en el login

Sounds good to me.

**Comment by Goya01** [comment]
> Podemos de una vez implementar un _Forgot Password Functionality_ en el login

I like this idea a lot. Would be great to implement in the login page.

**Comment by igrv2003** [comment]
Creo que tambien vendria bien implementar un Create Account Functionality, para usuarios que no tienen cuenta.

**Comment by Goya01** [comment]
> Creo que tambien vendria bien implementar un Create Account Functionality, para usuarios que no tienen cuenta.

Great Idea! Love it!
