### ISSUE TITLE
Chart dummy data change

### ISSUE THREAD

**Issue by fernandopizarro1** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#42]
### How
Currently, the charts are using a dummy array to be able to visualize them. `const [data] = useState([
    { category: 'Food', value: 300 },
    { category: 'Housing', value: 500 },
    { category: 'Entertainment', value: 200 },
    { category: 'Others', value: 100 },
  ]);`
The purpose of this issue is to change the dummy data in the charts to the data from the json files with the help of a partner. 
Priority 5 
Difficulty 3

**Comment by AngelMartinez33** [comment]
I can help!
