### ISSUE TITLE
UI Style Enhancement when in dark mode

### ISSUE THREAD

**Issue by AngelMartinez33** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#46]
To modify the styling of the expenses buttons so they look good in dark mode. The current buttons are unreadable with a dark background.

Difficulty: 3
Priority: 3

**Comment by AngelCIICMorales** [comment]
That is a great idea! Will you be doing this yourself or is someone else doing it?

**Comment by AngelMartinez33** [comment]
Thanks! I will do it.

**Comment by ActuallySeb** [comment]
I opened it and could not see the bars on the bar chart so this is good
