### ISSUE TITLE
Sign/Log in using Apple authentication

### ISSUE THREAD

**Issue by JeanMontesSantiago** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#63]
Objective:
Add the possibility for users to access their accounts using their Apple account for verification.

Requirements:
Allow the user to log in to their account.
Register a new user in the database.

Implementation Details:
Using Firebase, user authentication will be set up.

Difficulty: 4
Priority: 5

**Comment by dAninAd1248** [comment]
Being a member of the Apple Developer Program, which costs $100 a year, is required for this feature. I can ask for an education waiver, but this would take time.
