### ISSUE TITLE
Sign Out functionality

### ISSUE THREAD

**Issue by JeanMontesSantiago** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#66]
## Objective:
Allow the user to sign out of their account.

## Requirements:
The user should be able to press a button and log out of their account.
The account should not be deleted from the database.

### difficulty: 3

**Comment by JeanMontesSantiago** [comment]
Implemented in the "Sign/Log-in-Feature-Main-Branch".

**Comment by ActuallySeb** [comment]
Which branch is the "Sign/Log-in-Feature-Main-Branch" referring to, I can't find it in when I open the checkout

**Comment by ActuallySeb** [comment]
Found it
