### ISSUE TITLE
Data Visualization

### ISSUE THREAD

**Issue by AngelCIICMorales** [uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager#9]
What:
We're embarking on a project to relay users' data to them in an accessible format. Initially, our focus is on providing a visual depiction of users' financial resources and expenditure.

Why:
Our objective is to empower users with a lucid comprehension of their financial standing by illustrating their monetary flow and spending trends visually. This graphical representation equips users with insights to make informed decisions and enhance their financial management skills.

How:
To achieve this, we'll leverage the capabilities of the D3.js library. D3.js is a potent JavaScript tool designed for crafting dynamic and interactive data visualizations within web environments. Utilizing common web standards such as HTML, CSS, and Scalable Vector Graphics (SVG), D3.js enables us to create intuitive representations of users' financial data.

**Comment by MarkoSchuetz** [comment]
Is this really the right size to start working on? What if you break it down some more: for example, a pie chart shows the expenditures by categories by default for the last month, but the period can be set by the user. I'm not suggesting that this particular feature should be on your project, but just giving this as an example of the task size that you could aim for.

**Comment by AngelCIICMorales** [comment]
I understand your concern. We are going to start with a simple bar chart that will work in a ratio. The more money you earn in comparison to spent the bigger the bar. You will have 3 bars. Money earned, money spent, and total income.

**Comment by fernandopizarro1** [comment]
We could also implement a pie chart that compares the income and the expenses input by the user, and we could add this after the bar chart is done.
